# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b3f299adebc552a92440d243c45cd5230a5c615df92060c55ec950b920124208ff30980ad1d661bbe9316112d791a041deb3b6f4aa1153b56b69f675a172a1e

test:
  secret_key_base: 1d4e0b32ec9434225841eeda4cea89b8c9f98205448ecaf66adcda723788c5ed4d4e5be3df568beb0e44804068835228fcdddea404a01a4d6075f649715e7a43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
